-- Normalisation des téléphones vides. **NE CRÉE PLUS L'INDEX UNIQUE.**
--
-- ⚠️ LE NOM DU DOSSIER MENT, ET C'EST DÉLIBÉRÉ.
--
-- Ce répertoire s'appelle `user_phone_unique` et ne pose aucune contrainte
-- d'unicité. Le renommer serait plus honnête mais casserait la production :
-- cette migration y est enregistrée **en échec** dans `_prisma_migrations`, et
-- un nom de dossier qui disparaît laisse une entrée orpheline que Prisma refuse
-- ensuite de dépiler. On garde le nom, et on écrit ici ce que le nom ne dit pas.
--
-- ## Ce qui s'est passé
--
-- La première version normalisait PUIS créait un index unique partiel, derrière
-- un bloc qui levait une exception explicite si des numéros réels étaient
-- partagés. Elle a fait exactement cela en production, le 21/09/2026 : trois
-- numéros portés par dix comptes, migration interrompue, déploiement bloqué.
--
-- Le garde-fou a fonctionné — il valait mieux que le message générique de
-- PostgreSQL, et infiniment mieux qu'une contrainte silencieusement absente.
-- Mais livrer une migration dont on sait qu'elle échouera n'est pas une
-- stratégie de déploiement : deux des trois groupes contiennent des comptes
-- AVEC des commandes, qu'on ne peut ni supprimer (pièces comptables) ni fusionner
-- sans arbitrage humain.
--
-- ## Ce qui reste, et pourquoi
--
-- La normalisation seule. Elle est le temps (1) du plan en trois temps écrit
-- dans `schema.prisma` : `''` n'échappe pas à l'unicité en PostgreSQL, là où
-- `NULL` le fait — tant que des chaînes vides traînent, aucune contrainte n'est
-- posable, même sur une base sans vrai doublon.
--
-- Idempotente, et déjà sans effet en production (0 chaîne vide au 21/09/2026).
-- Elle est conservée parce qu'elle protège l'avenir : une écriture hors service
-- qui réintroduirait des `''` rendrait l'unicité impossible à nouveau.
--
-- ## Ce qui reste à faire, hors migration
--
--   node scripts/db/audit-phone-duplicates.js   # la liste nominative
--
-- Arbitrer chaque groupe — garder un compte, anonymiser les autres via
-- `UserDeletionService` —, puis poser l'index dans une migration dédiée. En
-- attendant, l'abus reste fermé par le signal `PHONE_REUSED` du scoring de
-- parrainage, qui envoie la récompense en revue humaine.

UPDATE "User" SET "phone" = NULL WHERE "phone" = '';
