# render.yaml
# A placer à la racine de votre projet C:\Users\fatak\lilia-app

services:
  # Le service pour l'API NestJS
  - type: web
    name: lilia-app-backend
    runtime: node
    plan: free # ou standard, etc.
    buildCommand: "npm install && npm run build"
    startCommand: "npx prisma migrate deploy && node dist/main.js"
    healthCheckPath: /api # Important: changez ceci pour une route qui existe (ex: /api pour Swagger)
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lilia-db # Doit correspondre au nom du service de DB ci-dessous
          property: connectionString
      - key: NODE_ENV
        value: production
      # --- Ajoutez vos autres secrets ici ---
      # Il est plus sécurisé de les ajouter via le tableau de bord Render
      # que de les mettre en clair dans ce fichier.
      # - key: FIREBASE_API_KEY
      #   value: votre_valeur
      # - key: CLOUDINARY_URL
      #   value: votre_valeur

  # Le service pour la base de données PostgreSQL
  - type: psql
    name: lilia-db
    plan: free # ou un plan payant pour plus de performance/stockage
    # La version de PostgreSQL peut être spécifiée si besoin
    # postgresqlVersion: 14
