import { collectAdminRoutes } from '../../../test/admin-routes';

/**
 * F3-08 — classement de TOUTES les routes ouvertes au rôle ADMIN.
 *
 * Chaque route porte soit une capacité (`@RequireCapability`), soit `NONE`
 * (tout administrateur). Une route nouvelle non classée fait échouer ce test :
 * il faut décider, en la créant, si elle fait partir de l'argent (motif
 * `cors-allowed-headers.spec.ts`). La liste vient des métadonnées Nest des
 * contrôleurs, pas d'une énumération tenue à la main.
 *
 * - FINANCE_EXECUTE : fait partir de l'argent, ou fixe ce qui revient à
 *   quelqu'un (commission, points, avoir, paiement déclaré reçu).
 * - FINANCE_APPROVE : second administrateur d'un geste financier.
 * - USER_ROLES : rôles, bannissements, capacités.
 * - SETTINGS : paramètres plateforme, grille de livraison, codes promo.
 */
const ADMIN_ROUTE_CAPABILITIES: Record<string, string> = {
  'AdminController.adjustClientLoyalty': 'FINANCE_EXECUTE',
  'AdminController.approveVendor': 'NONE',
  'AdminController.banUser': 'USER_ROLES',
  'AdminController.createRestaurantWithOwner': 'NONE',
  'AdminController.deleteReview': 'NONE',
  'AdminController.getActiveOrders': 'NONE',
  'AdminController.getAllClients': 'NONE',
  'AdminController.getAllDeliverers': 'NONE',
  'AdminController.getAllOrders': 'NONE',
  'AdminController.getAllRestaurants': 'NONE',
  'AdminController.getAllReviews': 'NONE',
  'AdminController.getAllUsers': 'NONE',
  'AdminController.getAllVendors': 'NONE',
  'AdminController.getAuditLog': 'NONE',
  'AdminController.getClientLoyalty': 'NONE',
  'AdminController.getClientReferral': 'NONE',
  'AdminController.getDashboardStats': 'NONE',
  'AdminController.getDelivererMissions': 'NONE',
  'AdminController.getDelivererStats': 'NONE',
  'AdminController.getLoyaltyDrifts': 'NONE',
  'AdminController.getPaymentsStats': 'NONE',
  'AdminController.getPendingVendors': 'NONE',
  'AdminController.getUserById': 'NONE',
  'AdminController.listPayments': 'NONE',
  'AdminController.listReferralRewards': 'NONE',
  'AdminController.reviewReferralReward': 'FINANCE_EXECUTE',
  'AdminController.suspendVendor': 'NONE',
  'AdminController.unbanUser': 'USER_ROLES',
  'AdminController.unsuspendVendor': 'NONE',
  'AdminController.updateUserRole': 'USER_ROLES',
  'AdminDeliveryFailureController.conclude': 'FINANCE_EXECUTE',
  'AdminDeliveryFailureController.evidence': 'NONE',
  'AdminDeliveryTariffsController.create': 'SETTINGS',
  'AdminDeliveryTariffsController.findOne': 'NONE',
  'AdminDeliveryTariffsController.list': 'NONE',
  'AdminDeliveryTariffsController.publish': 'SETTINGS',
  'AdminDeliveryTariffsController.remove': 'SETTINGS',
  'AdminDeliveryTariffsController.simulate': 'NONE',
  'AdminDeliveryTariffsController.update': 'SETTINGS',
  'AdminDriversController.activate': 'NONE',
  'AdminDriversController.create': 'NONE',
  'AdminDriversController.deactivate': 'NONE',
  'AdminDriversController.findAll': 'NONE',
  'AdminDriversController.findOne': 'NONE',
  'AdminDriversController.resendInvitation': 'NONE',
  'AdminDriversController.update': 'NONE',
  'AdminDriverSettlementsController.cancel': 'FINANCE_EXECUTE',
  'AdminDriverSettlementsController.list': 'NONE',
  'AdminDriverSettlementsController.outstanding': 'NONE',
  'AdminDriverSettlementsController.record': 'FINANCE_EXECUTE',
  'AdminOrderRefundsController.create': 'FINANCE_EXECUTE',
  'AdminOrderRefundsController.quote': 'NONE',
  'AdminPayoutController.getFinancials': 'NONE',
  'AdminPayoutController.listPayouts': 'NONE',
  'AdminPayoutController.payoutEvents': 'NONE',
  'AdminPayoutController.pendingSummary': 'NONE',
  'AdminPayoutController.requestPayout': 'FINANCE_EXECUTE',
  'AdminPayoutController.retryPayout': 'FINANCE_EXECUTE',
  'AdminPayoutController.updatePayoutAccount': 'FINANCE_EXECUTE',
  'AdminPayoutController.vendorPayoutAccounts': 'NONE',
  'AdminPayoutController.webhookHealth': 'NONE',
  'AdminPublicHolidaysController.create': 'NONE',
  'AdminPublicHolidaysController.list': 'NONE',
  'AdminPublicHolidaysController.remove': 'NONE',
  'AdminVendorOnboardingController.activate': 'NONE',
  'AdminVendorOnboardingController.create': 'NONE',
  'AdminVendorOnboardingController.resendInvitation': 'NONE',
  'AdminVendorOnboardingController.setDisplayOrder': 'NONE',
  'AdminVendorOnboardingController.setFeatured': 'NONE',
  'AdminVendorOnboardingController.updateCommerce': 'FINANCE_EXECUTE',
  'ApprovalsController.admins': 'NONE',
  'ApprovalsController.approve': 'FINANCE_APPROVE',
  'ApprovalsController.list': 'NONE',
  'ApprovalsController.reject': 'NONE',
  'ApprovalsController.requestCapabilities': 'USER_ROLES',
  'BannersController.create': 'NONE',
  'BannersController.remove': 'NONE',
  'BannersController.reorder': 'NONE',
  'BannersController.update': 'NONE',
  'CategoriesController.create': 'NONE',
  'CategoriesController.findAll': 'NONE',
  'CategoriesController.findOne': 'NONE',
  'CategoriesController.remove': 'NONE',
  'CategoriesController.reorder': 'NONE',
  'CategoriesController.update': 'NONE',
  'ClaimsController.findOne': 'NONE',
  'ClaimsController.list': 'NONE',
  'ClaimsController.postMessage': 'NONE',
  'ClaimsController.reject': 'NONE',
  'ClaimsController.voucher': 'FINANCE_EXECUTE',
  'CloudinaryController.uploadImage': 'NONE',
  'DashboardController.getClientDetail': 'NONE',
  'DashboardController.getClientStats': 'NONE',
  'DashboardController.getOrderStats': 'NONE',
  'DashboardController.getOverview': 'NONE',
  'DashboardController.getPeakHours': 'NONE',
  'DashboardController.getRestaurantRanking': 'NONE',
  'DashboardController.getRevenueChart': 'NONE',
  'DashboardController.getTopProducts': 'NONE',
  'DashboardController.getVendorStats': 'NONE',
  'DeliveriesController.assignDeliverer': 'NONE',
  'DeliveriesController.assignDelivererToOrder': 'NONE',
  'DeliveriesController.findAllForRestaurant': 'NONE',
  'DeliveriesController.findAssignmentHistory': 'NONE',
  'DeliveriesController.findByOrderId': 'NONE',
  'DeliveriesController.findOne': 'NONE',
  'DeliveriesController.getAvailableDeliverers': 'NONE',
  'DeliveriesController.updateStatus': 'NONE',
  'DeliveryFailureController.declare': 'NONE',
  'DeliveryReviewsController.create': 'NONE',
  'DeliveryReviewsController.findByDelivery': 'NONE',
  'DeliveryReviewsController.getDelivererStats': 'NONE',
  'DeliveryTariffsController.current': 'NONE',
  'IncidentsController.create': 'NONE',
  'IncidentsController.findAll': 'NONE',
  'IncidentsController.findOne': 'NONE',
  'IncidentsController.update': 'NONE',
  'MenuImagesController.create': 'NONE',
  'MenuImagesController.listMine': 'NONE',
  'MenuImagesController.remove': 'NONE',
  'MenuImagesController.reorder': 'NONE',
  'MenuImagesController.update': 'NONE',
  // F3-09 — éditeur d'options : écritures de catalogue, aucun argent en jeu.
  'ModifiersController.attach': 'NONE',
  'ModifiersController.availability': 'NONE',
  'ModifiersController.create': 'NONE',
  'ModifiersController.list': 'NONE',
  'ModifiersController.remove': 'NONE',
  'ModifiersController.reorder': 'NONE',
  'ModifiersController.update': 'NONE',
  'MenusController.create': 'NONE',
  'MenusController.findAllForAdmin': 'NONE',
  'MenusController.findByRestaurant': 'NONE',
  'MenusController.remove': 'NONE',
  'MenusController.toggleActive': 'NONE',
  'MenusController.update': 'NONE',
  'MenusController.updateStock': 'NONE',
  'OpsController.getQueue': 'NONE',
  'OrdersController.acceptOrder': 'NONE',
  'OrdersController.getPendingOrdersCount': 'NONE',
  'OrdersController.getReceipt': 'NONE',
  'OrdersController.getRestaurantOrders': 'NONE',
  'OrdersController.getStuckOrders': 'NONE',
  'OrdersController.getUserOrders': 'NONE',
  'OrdersController.rejectOrder': 'NONE',
  'OrdersController.updateOrderStatus': 'NONE',
  'PaymentController.confirmPayment': 'FINANCE_EXECUTE',
  'PaymentController.paymentEvents': 'NONE',
  'PaymentController.reconcile': 'NONE',
  'PaymentController.rejectPayment': 'FINANCE_EXECUTE',
  'PlatformSettingsController.get': 'NONE',
  'PlatformSettingsController.update': 'SETTINGS',
  'ProductImagesController.create': 'NONE',
  'ProductImagesController.listMine': 'NONE',
  'ProductImagesController.remove': 'NONE',
  'ProductImagesController.reorder': 'NONE',
  'ProductImagesController.update': 'NONE',
  'ProductsController.create': 'NONE',
  'ProductsController.findAllForOwner': 'NONE',
  'ProductsController.remove': 'NONE',
  'ProductsController.reorder': 'NONE',
  'ProductsController.setAvailability': 'NONE',
  'ProductsController.update': 'NONE',
  'ProductsController.updateStock': 'NONE',
  'PromoController.create': 'SETTINGS',
  'PromoController.findAll': 'NONE',
  'PromoController.remove': 'SETTINGS',
  'PromoController.stats': 'NONE',
  'PromoController.toggle': 'SETTINGS',
  'PromoController.validate': 'NONE',
  'QuartiersController.addQuartiersToZone': 'NONE',
  'QuartiersController.createDeliveryZone': 'NONE',
  'QuartiersController.deleteDeliveryZone': 'NONE',
  'QuartiersController.getMyDeliveryZones': 'NONE',
  'QuartiersController.removeQuartiersFromZone': 'NONE',
  'QuartiersController.seedQuartiers': 'NONE',
  'QuartiersController.setCentroid': 'NONE',
  'QuartiersController.updateDeliveryZone': 'NONE',
  'RefundsController.execute': 'FINANCE_EXECUTE',
  'RefundsController.findOne': 'NONE',
  'RefundsController.list': 'NONE',
  'RefundsController.updateStatus': 'FINANCE_EXECUTE',
  'RestaurantsController.addSpecialty': 'NONE',
  'RestaurantsController.countOrders': 'NONE',
  'RestaurantsController.create': 'NONE',
  'RestaurantsController.findClients': 'NONE',
  'RestaurantsController.findMine': 'NONE',
  'RestaurantsController.getClientOrders': 'NONE',
  'RestaurantsController.removeSpecialty': 'NONE',
  'RestaurantsController.setOperatingHours': 'NONE',
  'RestaurantsController.updateDeliverySettings': 'NONE',
  'RestaurantsController.updateOpenStatus': 'NONE',
  'RestaurantsController.updateOperatingHour': 'NONE',
  'RestaurantsController.updateRestaurant': 'NONE',
  'ScheduleController.checkHours': 'NONE',
  'ScheduleController.resetStock': 'NONE',
  'SmsController.sendTest': 'NONE',
  'VendorClosuresController.closedOnHolidays': 'NONE',
  'VendorClosuresController.create': 'NONE',
  'VendorClosuresController.list': 'NONE',
  'VendorClosuresController.opening': 'NONE',
  'VendorClosuresController.pause': 'NONE',
  'VendorClosuresController.remove': 'NONE',
  'VendorClosuresController.resume': 'NONE',
  'VendorOnboardingController.getDeliveryZones': 'NONE',
  'VendorOnboardingController.getOnboarding': 'NONE',
  'VendorOnboardingController.getPreview': 'NONE',
  'VendorOnboardingController.simulateDeliverySubsidy': 'NONE',
  'VendorOnboardingController.updateDelivery': 'NONE',
  'VendorOnboardingController.updateDeliverySubsidy': 'NONE',
  'VendorOnboardingController.updateHours': 'NONE',
  'VendorOnboardingController.updateIdentity': 'NONE',
  'VendorOnboardingController.updateLocation': 'NONE',
  'VendorPhotosController.create': 'NONE',
  'VendorPhotosController.listMine': 'NONE',
  'VendorPhotosController.remove': 'NONE',
  'VendorPhotosController.reorder': 'NONE',
  'VendorPhotosController.update': 'NONE',
  'VendorsController.approve': 'NONE',
  'VendorsController.create': 'NONE',
  'VendorsController.updateProfile': 'NONE',
};

describe('Classement des routes ADMIN (F3-08)', () => {
  const routes = collectAdminRoutes();

  it('aucune route ADMIN non classée, aucune entrée orpheline', () => {
    const actual = routes.map((r) => r.key);
    expect(actual.filter((k) => !(k in ADMIN_ROUTE_CAPABILITIES))).toEqual([]);
    expect(
      Object.keys(ADMIN_ROUTE_CAPABILITIES).filter((k) => !actual.includes(k)),
    ).toEqual([]);
  });

  it('chaque route porte exactement la capacité de la table', () => {
    const mismatches = routes
      .filter(
        (r) => (r.capability ?? 'NONE') !== ADMIN_ROUTE_CAPABILITIES[r.key],
      )
      .map((r) => `${r.key} : ${r.capability ?? 'NONE'}`);
    expect(mismatches).toEqual([]);
  });

  it('les gestes qui font partir de l’argent exigent FINANCE_EXECUTE', () => {
    for (const key of [
      'AdminPayoutController.requestPayout',
      'AdminPayoutController.updatePayoutAccount',
      'RefundsController.execute',
      'ClaimsController.voucher',
      'PaymentController.confirmPayment',
    ]) {
      expect(ADMIN_ROUTE_CAPABILITIES[key]).toBe('FINANCE_EXECUTE');
    }
  });
});
